const $=s=>document.querySelector(s);
const marker=$('#marker'),trackWrap=$('#trackWrap'),track=$('.track'),stage=$('#stage');
const positionEl=$('#position'),speedEl=$('#speed'),statusEl=$('#status'),instruction=$('#instruction'),instructionHint=$('#instructionHint'),timeLeftEl=$('#timeLeft'),elapsedEl=$('#elapsed'),progressText=$('#progressText'),progressFill=$('#progressFill'),cyclesEl=$('#cycles'),bpmReadout=$('#bpmReadout'),summary=$('#summary'),summaryStats=$('#summaryStats'),modeName=$('#modeName'),targetName=$('#targetName'),zoneLabel=$('#zoneLabel');
const startBtn=$('#startBtn'),pauseBtn=$('#pauseBtn'),resetBtn=$('#resetBtn'),restartBtn=$('#restartBtn');
const controls={targetType:$('#targetType'),mode:$('#mode'),orientation:$('#orientation'),duration:$('#duration'),minSpeed:$('#minSpeed'),maxSpeed:$('#maxSpeed'),minPause:$('#minPause'),maxPause:$('#maxPause'),pauseChance:$('#pauseChance'),variation:$('#variation'),bpm:$('#bpm'),haptics:$('#haptics'),reduceMotion:$('#reduceMotion')};
const outputs={duration:$('#durationValue'),minSpeed:$('#minSpeedValue'),maxSpeed:$('#maxSpeedValue'),minPause:$('#minPauseValue'),maxPause:$('#maxPauseValue'),pauseChance:$('#pauseChanceValue'),variation:$('#variationValue'),bpm:$('#bpmValue')};
const labels={mouth:'Bouche',vagina:'Vagin',anus:'Anus',custom:'Personnalisée',steady:'Régulier',random:'Aléatoire',stopgo:'Stop & Go',progressive:'Progressif',endurance:'Endurance',rhythm:'Rythme'};
const KEY='video-rytme-v6';
let pos=0,direction=1,target=1,speed=0,targetSpeed=120,running=false,paused=false,manualPause=false,pauseUntil=0,lastTime=0,nextSpeedChange=0,startTime=0,elapsedBeforePause=0,cycles=0,totalDistance=0,lastPauseAt=-Infinity;
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;
function setInstruction(a,b){instruction.textContent=a;instructionHint.textContent=b}
function horizontal(){return controls.orientation.value==='horizontal'}
function cfg(){return{min:+controls.minSpeed.value,max:+controls.maxSpeed.value,pmin:+controls.minPause.value,pmax:+controls.maxPause.value,chance:+controls.pauseChance.value/100,bpm:+controls.bpm.value,duration:+controls.duration.value*60,mode:controls.mode.value}}
function save(){try{const d={};Object.entries(controls).forEach(([k,v])=>d[k]=v.type==='checkbox'?v.checked:v.value);localStorage.setItem(KEY,JSON.stringify(d))}catch{}}
function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||'{}');Object.entries(controls).forEach(([k,v])=>{if(d[k]!==undefined)v.type==='checkbox'?v.checked=!!d[k]:v.value=d[k]})}catch{}}
function updateOutputs(){outputs.duration.textContent=`${controls.duration.value} min`;outputs.minSpeed.textContent=`${(+controls.minSpeed.value).toFixed(2)}×`;outputs.maxSpeed.textContent=`${(+controls.maxSpeed.value).toFixed(2)}×`;outputs.minPause.textContent=`${(+controls.minPause.value).toFixed(1)} s`;outputs.maxPause.textContent=`${(+controls.maxPause.value).toFixed(1)} s`;outputs.pauseChance.textContent=`${controls.pauseChance.value}%`;outputs.variation.textContent=`${controls.variation.value}%`;outputs.bpm.textContent=controls.bpm.value;bpmReadout.textContent=`${controls.bpm.value} BPM`;modeName.textContent=labels[controls.mode.value]||controls.mode.value;targetName.textContent=labels[controls.targetType.value]||controls.targetType.value;zoneLabel.textContent=`ZONE : ${(labels[controls.targetType.value]||controls.targetType.value).toUpperCase()}`;save()}
function axis(){const a=track.getBoundingClientRect(),b=trackWrap.getBoundingClientRect();return horizontal()?{start:a.left-b.left,end:a.right-b.left,center:a.top-b.top+a.height/2}:{start:a.top-b.top,end:a.bottom-b.top,center:a.left-b.left+a.width/2}}
function render(){const p=clamp(pos,0,1),a=axis();if(!Number.isFinite(a.start)||!Number.isFinite(a.end))return;if(horizontal()){marker.style.left=`${a.start+p*(a.end-a.start)}px`;marker.style.top=`${a.center}px`}else{marker.style.left=`${a.center}px`;marker.style.top=`${a.start+p*(a.end-a.start)}px`}marker.style.transform='translate3d(-50%,-50%,0)';positionEl.textContent=`${Math.round(p*100)}%`;speedEl.textContent=`${(speed/120).toFixed(2)}×`}
function apply(){stage.classList.toggle('horizontal',horizontal());requestAnimationFrame(render)}
function currentElapsed(now=performance.now()){return running?elapsedBeforePause+(now-startTime)/1000:elapsedBeforePause}
function chooseSpeed(now){const s=cfg();const min=Math.min(s.min,s.max),max=Math.max(s.min,s.max);targetSpeed=s.mode==='rhythm'?clamp(s.bpm*1.5,80,360):rand(min,max)*120;nextSpeedChange=now+(s.mode==='rhythm'?500:rand(1500,3500))}
function chooseTarget(){target=direction>0?1:0;setInstruction(direction>0?'Descendre vers 100%':'Remonter vers 0%',cfg().mode==='rhythm'?`Suis le tempo : ${cfg().bpm} BPM`:'Mouvement continu')}
function haptic(p){if(controls.haptics.checked&&navigator.vibrate)navigator.vibrate(p)}
function beginPause(now){const s=cfg();paused=true;pauseUntil=now+rand(Math.max(1,s.pmin),Math.max(1,s.pmax))*1000;lastPauseAt=now;marker.classList.add('paused');statusEl.textContent='PAUSE';setInstruction('PAUSE',`Reprise dans ${((pauseUntil-now)/1000).toFixed(1)} s`);haptic([30,40,30])}
function shouldPause(now){const s=cfg();return s.mode==='stopgo'&&now-lastPauseAt>=6000}
function updateTimer(now){const s=cfg(),e=currentElapsed(now),left=Math.max(0,s.duration-e),pct=clamp(e/s.duration*100,0,100);timeLeftEl.textContent=fmt(left);elapsedEl.textContent=fmt(e);progressText.textContent=`${Math.round(pct)}%`;progressFill.style.width=`${pct}%`;if(e>=s.duration)finish()}
function frame(now){if(!lastTime)lastTime=now;const dt=Math.min(.05,Math.max(0,now-lastTime)/1000);lastTime=now;if(running){updateTimer(now);if(running&&!paused){if(now>=nextSpeedChange)chooseSpeed(now);speed+=(targetSpeed-speed)*(1-Math.exp(-dt/.35));const length=Math.max(1,horizontal()?track.clientWidth:track.clientHeight);let next=pos+direction*(speed*dt/length);let reached=false;if(direction>0&&next>=1){next=1;reached=true}else if(direction<0&&next<=0){next=0;reached=true}pos=next;if(reached){if(direction<0)cycles++;cyclesEl.textContent=cycles;if(shouldPause(now)){beginPause(now)}else{direction=-direction;chooseTarget()}}}else if(paused&&!manualPause){const remain=Math.max(0,pauseUntil-now);instructionHint.textContent=`Reprise dans ${(remain/1000).toFixed(1)} s`;if(now>=pauseUntil){paused=false;marker.classList.remove('paused');statusEl.textContent='EN COURS';direction=-direction;chooseTarget()}}}render();requestAnimationFrame(frame)}
function start(){if(running)return;summary.hidden=true;running=true;paused=false;manualPause=false;pos=0;direction=1;target=1;speed=0;cycles=0;totalDistance=0;lastPauseAt=-Infinity;cyclesEl.textContent='0';marker.classList.remove('paused');const now=performance.now();startTime=now;elapsedBeforePause=0;lastTime=now;chooseSpeed(now);chooseTarget();statusEl.textContent='EN COURS';startBtn.disabled=true;pauseBtn.disabled=false;pauseBtn.textContent='PAUSE';render();haptic(25)}
function togglePause(){if(!running&&!paused)return;if(!paused){elapsedBeforePause=currentElapsed();running=false;paused=true;manualPause=true;marker.classList.add('paused');statusEl.textContent='PAUSE MANUELLE';setInstruction('EN PAUSE','Appuie sur REPRENDRE');pauseBtn.textContent='REPRENDRE'}else{running=true;paused=false;manualPause=false;marker.classList.remove('paused');startTime=performance.now();lastTime=startTime;statusEl.textContent='EN COURS';setInstruction(direction>0?'Descendre vers 100%':'Remonter vers 0%','Mouvement continu');pauseBtn.textContent='PAUSE';requestAnimationFrame(frame);haptic(20)}}
function finish(){if(!running)return;elapsedBeforePause=cfg().duration;running=false;paused=false;manualPause=false;marker.classList.remove('paused');statusEl.textContent='TERMINÉ';startBtn.disabled=false;pauseBtn.disabled=true;pauseBtn.textContent='PAUSE';setInstruction('Séance terminée','La séance est terminée');summaryStats.innerHTML=`<div class="stat"><span>Durée</span><strong>${fmt(elapsedBeforePause)}</strong></div><div class="stat"><span>Cycles</span><strong>${cycles}</strong></div><div class="stat"><span>Distance</span><strong>${Math.round(totalDistance*100)}%</strong></div><div class="stat"><span>Mode</span><strong>${labels[controls.mode.value]}</strong></div>`;summary.hidden=false;haptic([60,40,60])}
function reset(){running=false;paused=false;manualPause=false;pos=0;direction=1;target=1;speed=0;targetSpeed=120;cycles=0;totalDistance=0;elapsedBeforePause=0;lastPauseAt=-Infinity;lastTime=performance.now();marker.classList.remove('paused');statusEl.textContent='PRÊT';setInstruction('Appuie sur START','Le mouvement commencera à 0 %.');startBtn.disabled=false;pauseBtn.disabled=true;pauseBtn.textContent='PAUSE';summary.hidden=true;cyclesEl.textContent='0';timeLeftEl.textContent=fmt(cfg().duration);elapsedEl.textContent='00:00';progressText.textContent='0%';progressFill.style.width='0%';render()}
function applyPreset(name){const p={soft:{mode:'steady',duration:8,minSpeed:.4,maxSpeed:1,pauseChance:0},beginner:{mode:'progressive',duration:10,minSpeed:.4,maxSpeed:1.2,pauseChance:0},rhythm:{mode:'rhythm',duration:8,minSpeed:.7,maxSpeed:1.8,pauseChance:0},intense:{mode:'endurance',duration:12,minSpeed:1.2,maxSpeed:2.6,pauseChance:0},random:{mode:'random',duration:7,minSpeed:.5,maxSpeed:2.2,pauseChance:0}}[name];if(!p)return;Object.entries(p).forEach(([k,v])=>controls[k].value=v);document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===name));updateOutputs();reset()}
Object.values(controls).forEach(el=>el.addEventListener('input',()=>{updateOutputs();if(!running&&!paused)reset()}));controls.orientation.addEventListener('change',apply);startBtn.addEventListener('click',start);pauseBtn.addEventListener('click',togglePause);resetBtn.addEventListener('click',reset);restartBtn.addEventListener('click',()=>{reset();start()});document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>applyPreset(b.dataset.preset)));window.addEventListener('resize',render);document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)togglePause()});document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();if(running||paused)togglePause();else start()}if(e.key==='r'||e.key==='R')reset});load();updateOutputs();apply();reset();requestAnimationFrame(frame);